### ISSUE TITLE
xsdata seems to have an issue with metadata = {"type": "ignore"}

### ISSUE THREAD

**Issue by skinkie** [tefra/xsdata#1091]
[testcase.zip](https://github.com/user-attachments/files/17680506/testcase.zip)

Running the code below result into.
```
This works
WheelchairAccess(value=<LimitationStatusEnumeration.FALSE: 'false'>)
This fails
Told you so...
Traceback (most recent call last):
  File "/tmp/xsdata_bug.py", line 22, in <module>
    print(site_frame.stop_places.stop_place[0].accessibility_assessment.limitations.accessibility_limitation)
  File "/usr/lib/python3.12/dataclasses.py", line 262, in wrapper
    result = user_function(self)
             ^^^^^^^^^^^^^^^^^^^
  File "<string>", line 3, in __repr__
AttributeError: 'AccessibilityLimitation' object has no attribute 'validity_conditions_or_valid_between'
```

Removing the attributes with type=ignore, the code functions as expected.
```python
@dataclass(kw_only=True)
class AccessibilityLimitation(AccessibilityLimitationVersionedChildStructure):
    class Meta:
        namespace = "http://www.netex.org.uk/netex"

    validity_conditions_or_valid_between: Any = field(
        init=False,
        metadata={
            "type": "Ignore",
        },
    )
    alternative_texts: Any = field(
        init=False,
        metadata={
            "type": "Ignore",
        },
    )
```

```python
from pathlib import Path

from xsdata.formats.dataclass.context import XmlContext
from xsdata.formats.dataclass.parsers import XmlParser
from xsdata.formats.dataclass.parsers.config import ParserConfig
from xsdata.formats.dataclass.parsers.handlers import LxmlEventHandler

from netex import PublicationDelivery, CompositeFrame, SiteFrame

context = XmlContext()
config = ParserConfig(fail_on_unknown_properties=False)
parser = XmlParser(context=context, config=config, handler=LxmlEventHandler)
pd = parser.parse(Path("/tmp/smaller.xml"), PublicationDelivery)
composite_frame: CompositeFrame = pd.data_objects.choice[0]
site_frame: SiteFrame = composite_frame.frames.common_frame[1]

print("This works")
print(site_frame.stop_places.stop_place[0].accessibility_assessment.limitations.accessibility_limitation.wheelchair_access)

print("This fails")
try:
    print(site_frame.stop_places.stop_place[0].accessibility_assessment.limitations.accessibility_limitation)
except:
    print("Told you so...")
    raise

print("Therefore this fails too")
try:
    print(site_frame.stop_places.stop_place[0])
except:
    print("Told you so...")
    raise
```

**Comment by tefra** [comment]
Pleased provide a simple example for me @skinkie

**Comment by skinkie** [comment]
@tefra the zip file attached contains everything, _except_ for the generated NeTEx.

This is everything, just run xsdata_bug.py.
[everything.zip](https://github.com/user-attachments/files/17686441/everything.zip)

**Comment by skinkie** [comment]
> Pleased provide a simple example for me @skinkie

I read your other comment, I'll see how I can simplify. I wish there was some easy XML Schema GUI tooling for Linux as well.

**Comment by skinkie** [comment]
@tefra small enough?

[small-example.zip](https://github.com/user-attachments/files/17686620/small-example.zip)

**Comment by skinkie** [comment]
In addition, I notice that this also fails on objects using `dataclasses.asdict(obj)`, where getattr tries to get a field that has ignore. Trying to manually remove it did not resolve the issue so still investigating.

**Comment by skinkie** [comment]
Thanks for the effort!
