### ISSUE TITLE
'SerializerConfig' object has no attribute 'class_type'

### ISSUE THREAD

**Issue by skinkie** [tefra/xsdata#1110]
Reproducible example:
```
from xsdata.formats.dataclass.parsers.config import ParserConfig
from xsdata.formats.dataclass.serializers import XmlSerializer
from xsdata.formats.dataclass.serializers.config import SerializerConfig

serializer_config = SerializerConfig()
serializer = XmlSerializer(serializer_config)


from dataclasses import dataclass, field
from typing import Optional, Union

@dataclass(kw_only=True)
class Test:
    class Meta:
        namespace = "http://www.netex.org.uk/netex"

    id: Optional[str] = field(
        default=None,
        metadata={
            "type": "Elements",
            "choices": (
                {
                    "name": "Id",
                    "type": str,
                },
            ),
        },
    )

anfrage = serializer.render(Test(id='1'))
print(anfrage)
```

```
Traceback (most recent call last):
  File "/mnt/storage/home/skinkie/Sources/references/gtfs-netex-test/test-313.py", line 30, in <module>
    anfrage = serializer.render(Test(id='1'))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/venv/lib/python3.12/site-packages/xsdata/formats/dataclass/serializers/xml.py", line 40, in render
    self.write(output, obj, ns_map)
  File "/tmp/venv/lib/python3.12/site-packages/xsdata/formats/dataclass/serializers/xml.py", line 57, in write
    handler.write(events)
  File "/tmp/venv/lib/python3.12/site-packages/xsdata/formats/dataclass/serializers/writers/lxml.py", line 51, in write
    super().write(events)
  File "/tmp/venv/lib/python3.12/site-packages/xsdata/formats/dataclass/serializers/mixins.py", line 116, in write
    for name, *args in events:
                       ^^^^^^
  File "/tmp/venv/lib/python3.12/site-packages/xsdata/formats/dataclass/serializers/mixins.py", line 505, in generate
    if isinstance(obj, self.context.class_type.derived_element):
                       ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'SerializerConfig' object has no attribute 'class_type'
```

**Comment by skinkie** [comment]
Reproducible example:
```
from xsdata.formats.dataclass.parsers.config import ParserConfig
from xsdata.formats.dataclass.serializers import XmlSerializer
from xsdata.formats.dataclass.serializers.config import SerializerConfig

serializer_config = SerializerConfig(ignore_default_attributes=True)
serializer = XmlSerializer(serializer_config)


from dataclasses import dataclass, field
from typing import Optional, Union

@dataclass(kw_only=True)
class Test:
    class Meta:
        namespace = "http://www.netex.org.uk/netex"

    id: Optional[str] = field(
        default=None,
        metadata={
            "type": "Elements",
            "choices": (
                {
                    "name": "Id",
                    "type": str,
                },
            ),
        },
    )

anfrage = serializer.render(Test(id='1'))
print(anfrage)
```

```
Traceback (most recent call last):
  File "/mnt/storage/home/skinkie/Sources/references/gtfs-netex-test/test-313.py", line 30, in <module>
    anfrage = serializer.render(Test(id='1'))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/venv/lib/python3.12/site-packages/xsdata/formats/dataclass/serializers/xml.py", line 40, in render
    self.write(output, obj, ns_map)
  File "/tmp/venv/lib/python3.12/site-packages/xsdata/formats/dataclass/serializers/xml.py", line 57, in write
    handler.write(events)
  File "/tmp/venv/lib/python3.12/site-packages/xsdata/formats/dataclass/serializers/writers/lxml.py", line 51, in write
    super().write(events)
  File "/tmp/venv/lib/python3.12/site-packages/xsdata/formats/dataclass/serializers/mixins.py", line 116, in write
    for name, *args in events:
                       ^^^^^^
  File "/tmp/venv/lib/python3.12/site-packages/xsdata/formats/dataclass/serializers/mixins.py", line 505, in generate
    if isinstance(obj, self.context.class_type.derived_element):
                       ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'SerializerConfig' object has no attribute 'class_type'
```

**Comment by tefra** [comment]
You are passing the config as a positional argument, but the first one is supposed to be the XmlContext instance


```python
serializer = XmlSerializer(config=serializer_config)
```

**Comment by skinkie** [comment]
@tefra thanks for your prompt response. Even in this issue list #701  (and stackoverflow) there is an example that also makes this mistake. Is this recently changed?

**Comment by tefra** [comment]
Some refactoring happened to extract a parent class in v24.4.
