### ISSUE TITLE
UnicodeEncodeError while generating from utf8 .xsd

### ISSUE THREAD

**Issue by Shinigami9000** [tefra/xsdata#302]
I have been trying to generate classes using your library but i ran into the following problem while trying to generate
upa_2020_response.xsd

link to the responce
[https://www.sivi.org/upa_2020_response-2/](url)

I also ran into the same problem with the following .xsd's
[https://www.sivi.org/upa_2020_request-2/](url)
[https://www.sivi.org/upa_2021_response/](url)
[https://www.sivi.org/upa_2021_request-2/](url)

Could you take a look at this problem?

Hope to hear from you soon

kind regards,

Connor

`PS C:\Users\Connor.Deutz\AppData\Roaming\Python\Python38\Python_XML_Builder> xsdata .\xsd_format\upa_2020_response.xsd
Parsing schema upa_2020_response.xsd
Compiling schema upa_2020_response.xsd
Builder: 17 main and 1 inner classes       
Analyzer input: 17 main and 1 inner classes
Analyzer output: 9 main and 1 inner classes
Generating package: init
Generating package: generated.upa_2020_response
Traceback (most recent call last):

  File "c:\users\connor.deutz\appdata\local\programs\python\python38-32\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\connor.deutz\appdata\local\programs\python\python38-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Connor.Deutz\AppData\Local\Programs\Python\Python38-32\Scripts\xsdata.exe\__main__.py", line 7, in <module>
  File "c:\users\connor.deutz\appdata\local\programs\python\python38-32\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\connor.deutz\appdata\local\programs\python\python38-32\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\connor.deutz\appdata\local\programs\python\python38-32\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\connor.deutz\appdata\local\programs\python\python38-32\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\connor.deutz\appdata\local\programs\python\python38-32\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\connor.deutz\appdata\local\programs\python\python38-32\lib\site-packages\xsdata\cli.py", line 98, in generate
    transformer.process_schemas(list(uris))
  File "c:\users\connor.deutz\appdata\local\programs\python\python38-32\lib\site-packages\xsdata\codegen\transformer.py", line 68, in process_schemas
    self.process_classes()
  File "c:\users\connor.deutz\appdata\local\programs\python\python38-32\lib\site-packages\xsdata\codegen\transformer.py", line 91, in process_classes
    writer.write(classes)
  File "c:\users\connor.deutz\appdata\local\programs\python\python38-32\lib\site-packages\xsdata\codegen\writer.py", line 33, in write
    result.path.write_text(result.source)
  File "c:\users\connor.deutz\appdata\local\programs\python\python38-32\lib\pathlib.py", line 1252, in write_text
    return f.write(data)
  File "c:\users\connor.deutz\appdata\local\programs\python\python38-32\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\x80' in position 3234: character maps to <undefined>
PS C:\Users\Connor.Deutz\AppData\Roaming\Python\Python38\Python_XML_Builder> `

**Comment by tefra** [comment]
Hi @Shinigami9000 

I see you are on windows, let me try a few tests, it seems the pathlib is not using utf-8 to write the generated code.


What is the output of 

```
python -c 'import sys; print(sys.getdefaultencoding())'
```

can you try to export `PYTHONIOENCODING=UTF-8` in your console and try again?

**Comment by tefra** [comment]
Reproduced it 
https://github.com/tefra/xsdata/runs/1309868998?check_suite_focus=true

The fix is on master

**Comment by BlietZ** [comment]
Awesome quick response! Thanks tefra!

**Comment by Shinigami9000** [comment]
Thanks for the quick response! it works. Thanks tefra :D
