### ISSUE TITLE
Attribute values are parsed as qnames

### ISSUE THREAD

**Issue by eriks5** [tefra/xsdata#346]
If an attribute value looks like a qname, but isn't, serializing breaks.

Example:

```py
from dataclasses import dataclass, field

from xsdata.formats.dataclass.serializers import XmlSerializer
from xsdata.formats.dataclass.serializers.config import SerializerConfig


@dataclass
class Element:
    attr: str = field(metadata=dict(type="Attribute", name="attr"))


def test(value):
    element = Element(attr=value)
    config = SerializerConfig(pretty_print=True)
    serializer = XmlSerializer(config=config)
    print(serializer.render(element))


if __name__ == '__main__':
    test('{{}}')

```

When running the above script, lxml throws a `ValueError` exception:

```
Traceback (most recent call last):
  File "scratch.py", line 20, in <module>
    test('{{}}')
  File "scratch.py", line 16, in test
    print(serializer.render(element))
  File "env38.win\lib\site-packages\xsdata\formats\dataclass\serializers\xml.py", line 55, in render
    self.write(output, obj, ns_map)
  File "env38.win\lib\site-packages\xsdata\formats\dataclass\serializers\xml.py", line 70, in write
    handler.write(events)
  File "env38.win\lib\site-packages\xsdata\formats\dataclass\serializers\writers\lxml.py", line 18, in write
    super().write(events)
  File "env38.win\lib\site-packages\xsdata\formats\dataclass\serializers\mixins.py", line 82, in write
    self.end_tag(*args)
  File "env38.win\lib\site-packages\xsdata\formats\dataclass\serializers\mixins.py", line 170, in end_tag
    self.flush_start(True)
  File "env38.win\lib\site-packages\xsdata\formats\dataclass\serializers\mixins.py", line 206, in flush_start
    self.handler.startElementNS(self.pending_tag, None, self.attrs)
  File "src\lxml\sax.py", line 111, in lxml.sax.ElementTreeContentHandler.startElementNS
  File "src\lxml\etree.pyx", line 3022, in lxml.etree.Element
  File "src\lxml\apihelpers.pxi", line 131, in lxml.etree._makeElement
  File "src\lxml\apihelpers.pxi", line 118, in lxml.etree._makeElement
  File "src\lxml\apihelpers.pxi", line 215, in lxml.etree._setNodeNamespaces
  File "src\lxml\apihelpers.pxi", line 1755, in lxml.etree._uriValidOrRaise
ValueError: Invalid namespace URI '{'
```

Tested with versions 20.11.1 and 20.12

**Comment by tefra** [comment]
Thanks for reporting @eriks5 the fix is on master @ 8d77557
