### ISSUE TITLE
Data binding XML fails when using `xsi:type` to specify type in XML

### ISSUE THREAD

**Issue by wsot** [tefra/xsdata#349]
Using xsdata==20.12
Python 3.9.0
MacOSX

Issue:
When attempting to bind XML to the data classes using the attached XSD, XML, and test script I receive the error "Primitive node doesn't support child nodes!"

I haven't been able to pin down what exactly is the problem, but I got to this which seemed like the smallest example I could come up with.

XSD file:
```xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns="urn:mytestxml:r38"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" targetNamespace="urn:mytestxml:r38" version="r38">

    <xsd:simpleType name="ServiceOrderType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="Re-energisation"/>
            <xsd:enumeration value="De-energisation"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:complexType name="ServiceOrderTypeBase" abstract="true">
    </xsd:complexType>

    <xsd:complexType name="Envelope">
        <xsd:sequence>
            <xsd:element name="ServiceOrderType" type="ServiceOrderTypeBase"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="ElectricityServiceOrderType">
        <xsd:complexContent>
            <xsd:extension base="ServiceOrderTypeBase">
                <xsd:sequence>
                    <xsd:element name="WorkType" type="ServiceOrderType" />
                </xsd:sequence>
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>

    <xsd:element name="mytestxml" type="Envelope" />
</xsd:schema>

```

XML file:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<ase:mytestxml xmlns:ase="urn:mytestxml:r38"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<ServiceOrderType xsi:type="ase:ElectricityServiceOrderType">
		<WorkType>Re-energisation</WorkType>
	</ServiceOrderType>
</ase:mytestxml>
```

Python script:
```python
import pathlib

from xsdata.formats.dataclass.parsers import XmlParser
from xsdata.formats.dataclass.parsers.config import ParserConfig
from xsdata.formats.dataclass.parsers.handlers import LxmlEventHandler

from generated import mytestxml_r38

file = pathlib.Path("./myxml.xml").absolute()

xml_parser_config = ParserConfig(fail_on_unknown_properties=True)
xml_parser = XmlParser(config=xml_parser_config, handler=LxmlEventHandler)

xml_parser.from_path(file.absolute(), mytestxml_r38.Mytestxml)
```

Data classes were generated from the folder containing xml, xsd and py file with: `xsdata generate myxsd.xsd --ns-struct`
Then script was executed with `python ./mytest.py`

Full stack trace:
```
Traceback (most recent call last):
  File "/Volumes/CaseSensitiveDevPartition/docs-and-specs/xml-xsd/schemas/minimumsample/./mytest.py", line 18, in <module>
    xml_parser.from_path(file.absolute(), mytestxml_r38.Mytestxml)
  File "/Users/xxyyzz/.pyenv/versions/xsdata/lib/python3.9/site-packages/xsdata/formats/bindings.py", line 21, in from_path
    return self.parse(str(path.resolve()), clazz)
  File "/Users/xxyyzz/.pyenv/versions/xsdata/lib/python3.9/site-packages/xsdata/formats/dataclass/parsers/nodes.py", line 437, in parse
    result = handler.parse(source)
  File "/Users/xxyyzz/.pyenv/versions/xsdata/lib/python3.9/site-packages/xsdata/formats/dataclass/parsers/handlers/lxml.py", line 37, in parse
    return self.process_context(ctx)
  File "/Users/xxyyzz/.pyenv/versions/xsdata/lib/python3.9/site-packages/xsdata/formats/dataclass/parsers/handlers/lxml.py", line 44, in process_context
    self.parser.start(
  File "/Users/xxyyzz/.pyenv/versions/xsdata/lib/python3.9/site-packages/xsdata/formats/dataclass/parsers/xml.py", line 46, in start
    super().start(clazz, queue, objects, qname, attrs, ns_map)
  File "/Users/xxyyzz/.pyenv/versions/xsdata/lib/python3.9/site-packages/xsdata/formats/dataclass/parsers/nodes.py", line 458, in start
    child = item.child(qname, attrs, ns_map, len(objects))
  File "/Users/xxyyzz/.pyenv/versions/xsdata/lib/python3.9/site-packages/xsdata/formats/dataclass/parsers/nodes.py", line 401, in child
    raise XmlContextError("Primitive node doesn't support child nodes!")
xsdata.exceptions.XmlContextError: Primitive node doesn't support child nodes!
```

**Comment by tefra** [comment]
Thanks for reporting @wsot this fix is on master @ c0b2b32d45e79bded50b1cfbc6dc948eff096fee
